<option value="NCCM">National Certificate in Compter Repair and Mantenance</option>
<option value="NCEI">National Certificate in Electrical Installation</option>
<option value="NCBCP">National Certificate In Brick Laying And Concrete Practice</option>
<option value="NCTFD">National Certificate in Talioring and Fashion and Design</option>
<option value="DCS">Dilploma in Compter Science</option>
<option value="DIT">Diploma In information Technology</option>
<option value="DBA">Diploma In Business Administration</option>
<option value="NCAF">National Certificate in Accounting and Finence</option>
<option value="ECD">Early Childhood Development</option>
<option value="DPTE">Diploma in Primary Teaching Education</option>
<option value="DIT/Technical">Directorate of Industrial Training</option>
<option value="CNTT">Certificate in Nursery Teachers Training</option>
<option value="DAF">Diplma In Accounting and Finence</option>
<option value="NCHD">National Certificate in Hair Dressing</option>
<option value="NCCHM">National Certificate in Catering and Hotel Management</option>
<option value="NCICT">National Certificate in information and Communication Technology</option>
<option value="NCPC1">National Certificate In Plumbing year one</option>
<option value="NCAM">National Certificate In Automotive Mechanics</option>